name: Dave Amato
description: Web Engineer
avatar: https://cdn.amato.tk/profile.png

footer-links:
  dribbble:
  email: daveamato@live.com
  facebook:
  flickr:
  github: daveamato
  instagram:
  linkedin: dave-amato
  pinterest:
  rss: true
  twitter: daveamato
  stackoverflow:
  youtube:
  googleplus: # plus.google.com/XXXX

disqus:
google_analytics:  # UA-XXXXXXXZ-X

url: http://daveamato.github.io
baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded  # expanded or compressed

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
